### ISSUE TITLE
Process not switching the current working directory mentioned at "processCwd"

### ISSUE THREAD

**Issue by manju4ever** [bitsofinfo/stateful-process-command-proxy#10]
Here is my code

```
var Commander = require("stateful-process-command-proxy");

function _getNewExecutor(cwd) {
            var executor = new Commander({
                max:1,
                min:1,
                processCommand:"cmd.exe",
                logFunction: function(severity, origin, msg) {
                    //console.log(severity.toUpperCase()+ " "+ origin +" "+ msg);
                },
                 idleTimeoutMillis: 1000000,    
                 preDestroyCommands:["echo im going for a toss"],
                 processCwd: "../"
            });
            return executor;
}
```

It does not switch to previous directory

**Comment by bitsofinfo** [comment]
Fundamentally, whatever value you are putting for `processCwd` is ultimately passed to `child_process.spawn` as documented here (i.e. the `cwd` config value for spawn): https://nodejs.org/dist/latest-v4.x/docs/api/child_process.html#child_process_child_process_spawn_command_args_options

If its not working then its some detail with node and the way it launches a process and or however the cmd.exe executable interprets where its `cwd` should be (however that is done on windows I don't know).

An alternative workaround for you might just be to configure the `initCommands` property. There you could specify a `cd [PATH]` as an init command. You should be able to determine the true `cwd` in node, store that in a variable, then reference that variable in your `cd + varname` in the `initCommands` declaration.  

https://github.com/bitsofinfo/stateful-process-command-proxy/blob/master/statefulProcessCommandProxy.js#L67

**Comment by manju4ever** [comment]
Thank you so much @bitsofinfo , so i tried the **initCommands** way, it worked like a charm. But i did try to spawn a process manually, it works fine like as described in the official documentation. I also read your original source , seems pretty fine to me. 

For Reference: 
Node version: v5.5.0,
MS  Windows: Win 7 Enterprise x64

Closing this issue as there is a workaround available.

**Comment by bitsofinfo** [comment]
Please submit a pull-request if this needs some update for Node 5.x. This was last tested on 4.4.5 perhaps something is new in spawn?

https://github.com/bitsofinfo/stateful-process-command-proxy/blob/master/processProxy.js
