### ISSUE TITLE
Promise resolved prematurely for a process

### ISSUE THREAD

**Issue by manju4ever** [bitsofinfo/stateful-process-command-proxy#11]
Hi @bitsofinfo, i've been trying to run some maven tasks, and the executor executes the command and returns immediately. But the process will still be running in the background

please refer the output below: 

`{ command: 'mvn clean install -Dcucumber.options="--plugin com.cucumber.listener.ExtentCucumberFormatter:C:\\Users\\desapm\\Desktop\\launchpad-remote\\launch\\Service3\\reports\\57baab0a3a0c6ba41c7c484e/report.html C:\\Users\\desapm\\Desktop\\launchpad-remote\\launch\\Service3\\tests\\57baab0a3a0c6ba41c7c484e" > runout.txt',
  stdout: '',
  stderr: '' }`

stdout and stderr is empty.

**Comment by bitsofinfo** [comment]
Probably because maven is forking.

**Comment by tagyoureit** [comment]
I'm having a similar issue.  I'm trying to run `npm install` though this awesome module.  However, one of the modules (serialport - https://github.com/EmergingTechnologyAdvisors/node-serialport) spawns another process during the install to redownload/rebuild itself.  

Is there a way to capture the forking process?  

I tried to create a script like 

```
run_install ()
{
   echo "Running NPM install"
   npm install > result.txt
   cat result.txt
   echo "NPM install finished"
  return 0   # Success.
}
run_install
exit $?
```

but that didn't solve it either.  Thanks for any tips!
