### ISSUE TITLE
Issues with Powershell commands issued using Statefull Command Proxy Windows 10

### ISSUE THREAD

**Issue by OFSTalis** [bitsofinfo/stateful-process-command-proxy#14]
Node.js version: v4.2.6
Platform: Windows 64 bit
Subsystem: Windows 10 Pro

Hello, I was wondering if you may have an insight into my problem. I have been working on automated testing using Node.js on a Windows 7 machine which issues commands to a virtual machine using Powershell - this works as expected no problems. However, I have now upgraded to Windows 10 (no option to down grade again) and everything works fine except for Powershell commands. I can run commands by manually opening a powershell window, but commands contained within a script using the command proxy do not seem to work. The number of clients just seems to increase and they are never released (made available). I have included below the output from one of my scripts.

I can find no additional information in any windows logs.

Any help would be greatly appreciated

Regards

Talis

Using the selenium server at http://localhost:4444/wd/hub
 [launcher] Running 1 instances of WebDriver
 Started
 INFO PSCommandService Executing:
 Invoke-eXimiusTestAction -DatabaseName 'QA_Product_56_587_DATA' -DatabaseServer 'BEMECHE1SQL03\SQL2012' -ServiceName 'B-Misc' -MethodName 'BackupRestoreTable' -Parameters '{"BackupRestoreAction":"B","Table":"price","DeleteTableContent":"False"}'

INFO Pool dispense() clients=1 available=0
 INFO StatefulProcessCommandProxy create new process: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
 INFO ProcessProxy[null] Spawning process: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
 INFO ProcessProxy[null] Process: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe PID: 21752
 INFO PSCommandService Executing:
 Invoke-eXimiusTestAction -DatabaseName 'QA_Product_56_587_DATA' -DatabaseServer 'BEMECHE1SQL03\SQL2012' -ServiceName 'B-Misc' -MethodName 'BackupRestoreTable' -Parameters '{"BackupRestoreAction":"B","Table":"systemparameter","DeleteTableContent":"False"}'

INFO Pool dispense() clients=2 available=0
 INFO PSCommandService Executing:
 Invoke-eXimiusTestAction -DatabaseName 'QA_Product_56_587_DATA' -DatabaseServer 'BEMECHE1SQL03\SQL2012' -ServiceName 'B-Misc' -MethodName 'ExecuteSQL' -Parameters '{"Query":"update Price set PriceDateTime = ''2016-02-25 00:00:00.000'', PriceAmount_Am = ''6.500000'' where ObjID = ''29501CBB-FBC6-4F71-B244-4E84E54756DB''","QueryHash":"2016-11-14T15:31:48.664Z"}'

INFO Pool dispense() clients=3 available=0
 INFO PSCommandService Executing:
 Invoke-eXimiusTestAction -DatabaseName 'QA_Product_56_587_DATA' -DatabaseServer 'BEMECHE1SQL03\SQL2012' -ServiceName 'B-Misc' -MethodName 'ExecuteSQL' -Parameters '{"Query":"update Price set PriceDateTime = ''2016-02-25 00:00:00.000'', PricePercentage = ''100.000000000'' where ObjID = ''9FAA78E6-06B5-4EE5-B42F-FD49BC971AEF''","QueryHash":"2016-11-14T15:31:48.665Z"}'

INFO Pool dispense() clients=4 available=0
 INFO PSCommandService Executing:
 Invoke-eXimiusTestAction -DatabaseName 'QA_Product_56_587_DATA' -DatabaseServer 'BEMECHE1SQL03\SQL2012' -ServiceName 'B-Misc' -MethodName 'SetSystemParameter' -Parameters '{"ParameterName":"PortfolioBalanceDate","ParameterValue":"2016-02-25 00:00:00","TenantAware":"False"}'

INFO Pool dispense() clients=5 available=0

After this, the script hangs until the time out is reached.

**Comment by bitsofinfo** [comment]
I don't see any related errors here. My guess is that there must be a change in the way Windows 10 is handling the powershell commands you are invoking or the initialization commands you run in each shell as it it is spawned. If they are hanging then they are waiting on completion of the commands you are executing. I'd try manually executing everything exactly the same as you have everything configured, including any initialization commands.

**Comment by bitsofinfo** [comment]
duplicate https://github.com/bitsofinfo/powershell-command-executor/issues/5
