### ISSUE TITLE
How to do multiple command execution after connecting to Third party CLI?

### ISSUE THREAD

**Issue by Breme** [bitsofinfo/stateful-process-command-proxy#15]
I want to execute 5 commands in a sequence and log its output.For Example. First command XXXcli ip_address (This will connect me to the third party CLI mode) and the next commands will execute a script,the next will log output etc.But my problem is when I do SSH through node.js and spawn a shell inside ssh session, when I execute the first command I couldn't see any output on my Console. The Session creates a shell and once the shell enters the third party CLI ,Its becoming impossible for me to fire the next command or log the output of the first command.Kindly help me on this. I'm stuck with this for a long time

My Code:

`session.on('exec', function (accept, reject, info) {
                console.log('Client wants to execute: ' + inspect(info.command));
var stream = accept();

                     var cp = spawn('XXXCLI 10.21.254.12', {shell: true});

                     stream.stdin.pipe(cp.stdin);

                     cp.stdout.pipe(stream.stdout);

                sleep(6000);
                     cp.stderr.pipe(stream.stderr);

                     cp.on('exit', function (code, signal) {
                     stream.exit(signal || code);
                     }).on('end', function (code, signal) {
                     stream.close();

                     });

            });`
When I manually type the first command 'XXXCLI ip_address' in my command prompt and press enter,I will get a output "Connected to CLI...." .Once I get this connection successful, I need to execute my second command i.e "Lmc sample" which will load the master config and I will get the output as "Message sent..", third command will execute a script,will get output as "Message sent.." .This is what happens when I enter these commands manually in cmd prompt and execute.

What is happening is once I execute my first command i.e "XXXCLI 10.21.254.12" manually in cmd, The path where we actually execute the commands i.e( C:\users\CLI>) will not be visible. This happens because now it got connected with the above mentioned ip (10.21.254.12) .And Only after connecting to this ip ,I can able to execute my other commands.i.e command to load master config ,cmd to execute script etc.

So I want to execute my first command and get its stream in a variable and execute rest of the commands inside the stream created by first command Thanks!

**Comment by bitsofinfo** [comment]
How is this question related to this project? Have you tried using this library? because your example above it not using this library.
