### ISSUE TITLE
If commands have a mix of stderr and stdout output errors will occur

### ISSUE THREAD

**Issue by TrevTheDev** [bitsofinfo/stateful-process-command-proxy#16]
The code as it stands assumes stdout and stderr events occur sequentially.  If there are multiple commands in the queue, a subsequent commands stdout event may occur prior to the stderr event of a previous command.  These out of sequence events break the system.

One solution is to redirect all output to either stdout or stderr using e.g. 2>&1 - which seems to force events to occur in the right order.  This also means one will lose whether data was produced by stderr or stdout - to fix this echo $? as part of the done marker and read its state and move the data to the appropriate type on finish.

**Comment by bitsofinfo** [comment]
Please provide a working example of this issue.

**Comment by TrevTheDev** [comment]
The way I discovered this bug was by recursively stat'ing and then lsattr'ing each file in a directory tree (if you do this on /proc it will produce many errors which make it easy to spot the bug.).  The out of sequence return of stderr and stdout is considered a "feature" in Node.

**Comment by bitsofinfo** [comment]
If you'd like to contribute a PR to add a awareness note about in the README or some sort of code change feel free to submit a PR.
