### ISSUE TITLE
Child process received exit; code:null signal:SIGTERM

### ISSUE THREAD

**Issue by GlennQuirynen** [bitsofinfo/stateful-process-command-proxy#7]
Hi,
we are using the powershell execution very much in our automated testing framework (node.js & protractor/selenium).

We run over 300 tests, and almost with every test we use the powershell command to do changes on our back-end server (clear of cache, setting of configuration, ...).

All this works very fine, but we have seen some strange messages popping up in the command log when the tests are executed.

``` javascript
INFO Pool dispense() clients=2 available=0
INFO Pool dispense() clients=2 available=1
INFO Pool dispense() clients=1 available=1
INFO Pool dispense() clients=0 available=1
....INFO ProcessProxy[9572] C:\Windows\System32\WindowsPowerShell\v1,0\powershell.exe pid[9572] is shutting down...
INFO StatefulProcessCommandProxy process preDestroyCmd[Exit-PSSession] out: err:Command echo
INFO ProcessProxy[9572] child process received exit; code:null signal:SIGTERM
INFO ProcessProxy[9572] child process received close; code:null signal:SIGTERM
```

The first 4 lines (eg INFO Pool dispense() clients=2 available=0) are what we see every time, which I think is logical, as this gives information on the number of connections which are made.

But then we see the shutting down error, which should not occur right?
We only see this is a couple of time per run, but can you maybe give an explanation of this.

Is there maybe a time limit on how long a session can be open?
Or what can trigger the shutdown of a session?

**Comment by bitsofinfo** [comment]
Can you please post your config, i.e. how you are constructing your process proxy object?

i.e. `new StatefulProcessCommandProxy(....options)`

**Comment by GlennQuirynen** [comment]
Hi, 

please find below the initcode.
The referenced psssnapin is a custom snapin we developed.

``` javascript
var statefulProcessCommandProxy = new StatefulProcessCommandProxy( {
    name: "StatefulProcessCommandProxy",
    max: 1,
    min: 1,
    idleTimeoutMS: 120000,
    log: function (severity, origin, msg) {
        if (severity.toLowerCase() !== "verbose") {
            console.log(severity.toUpperCase() + " " + origin + " " + msg);
        }
    },

    logFunction : function (severity, origin, msg) { 
        if (severity.toLowerCase() !== "verbose") {
            console.log(severity.toUpperCase() + " " + origin + " " + msg);
        }
    },

    processCommand: 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe',
    processArgs: ['-Command', '-'],


    processRetainMaxCmdHistory : 20,
    processInvalidateOnRegex : {
        'any': [],
        'stdout': [],
        'stderr': [{ 'regex': '.*error.*' }]
    },
    processCwd : null,
    processEnvMap : null,
    processUid : null,
    processGid : null,


    // these commands will be run everytime the pool
    // instantiates a new shell, you may or may not
    // want to use this
    initCommands: [
        'Enter-PSSession -ComputerName ' + process.env.ServerName,
        'Add-PSSnapin eXimiusPowerShellSnapIn'
    ],


    validateFunction: function (processProxy) {
        var isValid = processProxy.isValid();
        if (!isValid) {
            console.log("ProcessProxy.isValid() returns FALSE!");
        }
        return isValid;
    },

    // these commands will be run everytime the pool
    // destroys a shell, you may or may not
    // want to use this
    preDestroyCommands: ['Exit-PSSession'],

    processCmdWhitelistRegex: [],

    processCmdBlacklistRegex: [],

    autoInvalidationConfig: null

});
``
```

**Comment by bitsofinfo** [comment]
Looks to me that this is just the underlying object pool destroying a ProcessProxy object that has been idle for >= your idleTimeout configuration: 

https://github.com/bitsofinfo/stateful-process-command-proxy/blob/master/statefulProcessCommandProxy.js#L179

**Comment by GlennQuirynen** [comment]
Ok. just to be sure :).

Thanks.

**Comment by bitsofinfo** [comment]
Feel free to submit a PR to add a small debug statement near https://github.com/bitsofinfo/stateful-process-command-proxy/blob/master/statefulProcessCommandProxy.js#L179 to better indicate that the POOL is actually destroying this for some reason

glad you are using the tool!

**Comment by bitsofinfo** [comment]
@GlennQuirynen , also if you are using powershell, you might want to look at this wrapper https://github.com/bitsofinfo/powershell-command-executor which can give you some higher level abstraction/protection and capabilities.

**Comment by GlennQuirynen** [comment]
Hi,

I am already using the wrapper as well :).
Thanks for building this very useful module.
We use it every day during our automated protractor tests.

Regards,
